name: macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Mac terminal
        run: |
          echo "ğŸ Mac aÃ§Ä±ldÄ±!"
          echo "------ Sistem ------"
          sw_vers
          system_profiler SPHardwareDataType

          echo "------ BulunduÄŸun klasÃ¶r ------"
          pwd

          echo "------ Dosyalar (Finder gibi) ------"
          ls -la

          echo "------ Ana dizin ------"
          cd /
          ls

          echo "Terminal aÃ§Ä±k kalÄ±yor..."
          sleep 3600
