name: macOS-new

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Mac terminal
        run: |
          echo "Mac acildi"
          echo "------ Sistem ------"
          sw_vers

          echo "------ Bulunduğun klasör ------"
          pwd

          echo "------ Proje dosyalari ------"
          ls -la

          echo "------ Kök dizin ------"
          cd /
          ls

          echo "------ Users klasörü ------"
          cd /Users
          ls

          echo "------ Kullanici klasörü ------"
          cd /Users/runner
          pwd
          ls -la

          echo "Terminal acik kaliyor..."
          sleep 3600
